/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotRouteRouteImport } from './routes/robot/route'
import { Route as IndexRouteImport } from './routes/index'

const RobotRouteRoute = RobotRouteRouteImport.update({
  id: '/robot',
  path: '/robot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robot': typeof RobotRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robot': typeof RobotRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robot': typeof RobotRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/robot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/robot'
  id: '__root__' | '/' | '/robot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotRouteRoute: typeof RobotRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robot': {
      id: '/robot'
      path: '/robot'
      fullPath: '/robot'
      preLoaderRoute: typeof RobotRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotRouteRoute: RobotRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
